### ISSUE TITLE
Occupancy Sensor

### ISSUE THREAD

**Issue by milad-soufastai** [MisterWil/abodepy#45] opened 2019-03-01 05:27 UTC
Looks like the Occupancy Sensor and the Temperature,Humidity, and Light sensor are considered the same so I see an error in my HA logs on every restart since the Occupancy Sensor doesn't provide Humidity information. 
`Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity_platform.py", line 352, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 244, in async_update_ha_state
    unit_of_measurement = self.unit_of_measurement
  File "/usr/src/app/homeassistant/components/abode/sensor.py", line 76, in unit_of_measurement
    return self._device.humidity_unit
  File "/usr/local/lib/python3.7/site-packages/abodepy/devices/sensor.py", line 44, in humidity_unit
    if CONST.UNIT_PERCENT in self._get_status(CONST.HUMI_STATUS_KEY):
TypeError: argument of type 'NoneType' is not iterable`

**Comment by pmcelreavy** [comment] 2019-07-18 17:40
I am seeing the same issue.

**Comment by shred86** [comment] 2019-10-12 03:05
Does the temp/humidity/light sensor show up as three separate devices in HA? Can someone post the JSON data from the occupancy sensor?

I think the issue is with the abode component in Home Assistant, specifically the `async_setup_entry` in sensor.py:

```
async def async_setup_entry(hass, config_entry, async_add_entities):
    """Set up a sensor for an Abode device."""

    data = hass.data[DOMAIN]

    devices = []
    for device in data.abode.get_devices(generic_type=CONST.TYPE_SENSOR):
        for sensor_type in SENSOR_TYPES:
            devices.append(AbodeSensor(data, device, sensor_type))

    async_add_entities(devices)
```

It looks to me the `for sensor_type in SENSOR_TYPES:` is simply iterating over the `SENSOR_TYPES` dictionary defined in the same sensor.py file:

```
SENSOR_TYPES = {
    "temp": ["Temperature", DEVICE_CLASS_TEMPERATURE],
    "humidity": ["Humidity", DEVICE_CLASS_HUMIDITY],
    "lux": ["Lux", DEVICE_CLASS_ILLUMINANCE],
}
```

...and appending each `SENSOR_TYPE` (i.e. temp, humidity and lux) without doing any sort of checking on the type of sensor it is. Seems like instead of the second `for sensor_type in SENSOR_TYPES:` loop, we would just need to check the `type_tag` passed from Abode and depending on what type of sensor it is, append it with that `sensor_type`.

**Comment by milad-soufastai** [comment] 2019-10-31 02:17
@shred86 Pulled a couple months ago but:{
    "id": "ZB:322b02",
    "type_tag": "device_type.lm",
    "type": "LM",
    "name": "Occupancy 1",
    "area": "1",
    "zone": "12",
    "sort_order": "",
    "is_window": "",
    "bypass": "0",
    "schar_24hr": "0",
    "sresp_24hr": "0",
    "sresp_mode_0": "0",
    "sresp_entry_0": "0",
    "sresp_exit_0": "0",
    "group_name": "Upstairs",
    "group_id": "382793",
    "default_group_id": "1",
    "sort_id": "4",
    "sresp_mode_1": "0",
    "sresp_entry_1": "0",
    "sresp_exit_1": "0",
    "sresp_mode_2": "0",
    "sresp_entry_2": "0",
    "sresp_exit_2": "0",
    "sresp_mode_3": "0",
    "uuid": "8ee12272b14b709e93732b9aecaff0ff",
    "sresp_entry_3": "0",
    "sresp_exit_3": "0",
    "sresp_mode_4": "0",
    "sresp_entry_4": "0",
    "sresp_exit_4": "0",
    "version": "POVS_00.00.03.18TC",
    "origin": "abode",
    "has_subscription": null,
    "onboard": "0",
    "s2_grnt_keys": "",
    "s2_dsk": "",
    "s2_propty": "",
    "s2_keys_valid": "",
    "zwave_secure_protocol": "",
    "control_url": "",
    "deep_link": null,
    "status_color": "#5cb85c",
    "faults": {
        "low_battery": 0,
        "tempered": 0,
        "supervision": 0,
        "out_of_order": 0,
        "no_response": 0,
        "jammed": 0,
        "zwave_fault": 0
    },
    "status": "70 \u00b0F",
    "statuses": {
        "temperature": "70 \u00b0F",
        "temp": "21.06",
        "lux": "9 lx"
    },
    "status_ex": "",
    "actions": [{
        "label": "High Temperature Alarm",
        "value": "a=1&z=12&trigger=TSH;"
    }, {
        "label": "Low Temperature Alarm",
        "value": "a=1&z=12&trigger=TSL;"
    }],
    "status_icons": [],
    "statusEx": "9",
    "icon": "assets\/icons\/occupancy-sensor.svg"
}, {
    "id": "ZB:322b01",
    "type_tag": "device_type.povs",
    "type": "Occupancy",
    "name": "Occupancy 1",
    "area": "1",
    "zone": "13",
    "sort_order": "",
    "is_window": "",
    "bypass": "0",
    "schar_24hr": "0",
    "sresp_24hr": "0",
    "sresp_mode_0": "0",
    "sresp_entry_0": "0",
    "sresp_exit_0": "0",
    "group_name": "Upstairs",
    "group_id": "382793",
    "default_group_id": "1",
    "sort_id": "5",
    "sresp_mode_1": "0",
    "sresp_entry_1": "0",
    "sresp_exit_1": "0",
    "sresp_mode_2": "0",
    "sresp_entry_2": "0",
    "sresp_exit_2": "0",
    "sresp_mode_3": "0",
    "uuid": "c3cca78a0c9c37db565f7feabd70fa4c",
    "sresp_entry_3": "0",
    "sresp_exit_3": "0",
    "sresp_mode_4": "0",
    "sresp_entry_4": "0",
    "sresp_exit_4": "0",
    "version": "POVS_00.00.03.18TC",
    "origin": "abode",
    "has_subscription": null,
    "onboard": "0",
    "s2_grnt_keys": "",
    "s2_dsk": "",
    "s2_propty": "",
    "s2_keys_valid": "",
    "zwave_secure_protocol": "",
    "control_url": "",
    "deep_link": null,
    "status_color": "#5cb85c",
    "faults": {
        "low_battery": 0,
        "tempered": 0,
        "supervision": 0,
        "out_of_order": 0,
        "no_response": 0,
        "jammed": 0,
        "zwave_fault": 0
    },
    "status": "Online",
    "statuses": {
        "motion": "0"
    },
    "status_ex": "",
    "actions": [],
    "status_icons": [],
    "sresp_trigger": "0",
    "sresp_restore": "0",
    "occupancy_timer": "30",
    "sensitivity": "4",
    "model": "L1",
    "is_motion_sensor": false,
    "icon": "assets\/icons\/motioncamera-a.svg"
}

It doesn't report humidity

**Comment by shred86** [comment] 2019-11-03 15:57
Hm, so there must be two versions of the Occupancy sensor. The [latest one](https://goabode.com/smart-home/smart-home-devices/occupancy-sensor) on their website reports humidity, lux and temp. Does anyone have the JSON for that one?

**Comment by shred86** [comment] 2019-11-05 00:49
@MisterWil This should be resolved with: https://github.com/home-assistant/home-assistant/pull/28516

**Closed** 2019-11-05 14:50 UTC
